name: 'build-test'
on: # rebuild any PRs and main branch changes
  [pull_request]

permissions:
  contents: read

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Package Manager Guard
        uses: safedep/pmg@v1
        with:
          server-mode: true
          api-key: ${{ secrets.SAFEDEP_API_KEY }}
          tenant-id: ${{ secrets.SAFEDEP_TENANT_ID }}
      - run: |
          npm install
      - run: |
          npm run all
      - name: Enforce PMG policy
        if: always()
        run: pmg proxy stop --fail-on-violation
  single-line-comment: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Package Manager Guard
        uses: safedep/pmg@v1
        with:
          server-mode: true
          api-key: ${{ secrets.SAFEDEP_API_KEY }}
          tenant-id: ${{ secrets.SAFEDEP_TENANT_ID }}
      - uses: ./
        with:
          comment: hello
      - uses: ./
        with:
          comment: hello
      - name: Enforce PMG policy
        if: always()
        run: pmg proxy stop --fail-on-violation
  multi-line-comment: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Package Manager Guard
        uses: safedep/pmg@v1
        with:
          server-mode: true
          api-key: ${{ secrets.SAFEDEP_API_KEY }}
          tenant-id: ${{ secrets.SAFEDEP_TENANT_ID }}
      - uses: ./
        with:
          comment: |
            ## What
            Hello old.
      - uses: ./
        with:
          check-only-first-line: true
          comment: |
            ## What
            Hello new.
      - uses: ./
        with:
          check-only-first-line: true
          comment: |
            ## What No match
            Hello.
      - name: Enforce PMG policy
        if: always()
        run: pmg proxy stop --fail-on-violation
